## Description: Download metadata for SCORES from the Google Spreadsheet.
##              Update the SID variable below when the deployment of the
##              Google Apps Script has changed.
##
##              Type "make" in this directory to download the JSON files for the metadata.
##

SID = AKfycbz1V58ZkIzowyu8FoOYt1EADP82_aCxYoVyrRxpyNWi0BQPZB1jlPcxrFRhbEzgtIA
all: download

download: works

works:
	curl -L "https://script.google.com/macros/s/$(SID)/exec?sheet=works" > works.json





